name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  Try_1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo Ahoj světe
      - run: echo Ahoj světe opět
  Try_2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo Ahoj světe 2!!!
  Try_3:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: [Try_1, Try_2]
    steps:
      - uses: actions/checkout@v2
      - run: echo Ahoj světe 3!!!

